In [184]:
!pip install gensim

In [185]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [186]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [187]:
#checking the different dimensions of the word king
vec_king = wv['king']
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [188]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection',sep='\t',names=["label","message"])

In [189]:
messages.shape

(5572, 2)

In [190]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [191]:
import re
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [266]:
# Filter out empty reviews
valid_indices = [i for i, doc in enumerate(corpus) if len(doc.strip()) > 0]

# Filter the original data accordingly
messages = messages.iloc[valid_indices].reset_index(drop=True)
corpus = [corpus[i] for i in valid_indices]

In [268]:
[[i,j,k]for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']) if i<1]

[]

In [270]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [272]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [274]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [275]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [278]:
import gensim

In [280]:
#Training Word2vec from scratch
model = gensim.models.Word2Vec(words)

In [281]:
## To Get All the Vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [282]:
model.corpus_count

5569

In [286]:
model.wv.similar_by_word('kid')

[('too', 0.9973530173301697),
 ('him', 0.997317373752594),
 ('said', 0.9971503615379333),
 ('yet', 0.9971451163291931),
 ('boy', 0.9971027374267578),
 ('many', 0.9970995187759399),
 ('one', 0.9970973134040833),
 ('we', 0.9970909357070923),
 ('out', 0.997078537940979),
 ('yeah', 0.9970552921295166)]

In [287]:
model.wv.similar_by_word('good')

[('all', 0.9987391233444214),
 ('morning', 0.9986537098884583),
 ('night', 0.9986531138420105),
 ('happy', 0.9985531568527222),
 ('my', 0.9985056519508362),
 ('wa', 0.9985045194625854),
 ('not', 0.9984808564186096),
 ('day', 0.9984645843505859),
 ('well', 0.9984630942344666),
 ('oh', 0.9983741044998169)]

In [290]:
# This function caluculates the average  of word2vec
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [292]:
!pip install tqdm

In [293]:
from tqdm import tqdm

In [294]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|                                                                                         | 0/5569 [00:00<?, ?it/s]C:\Users\Sushrutha\AppData\Roaming\Python\Python312\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Sushrutha\AppData\Roaming\Python\Python312\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:01<00:00, 5045.40it/s]


In [295]:
len(X)

5569

In [296]:
X

[array([-1.74621001e-01,  2.31070533e-01,  1.23805277e-01,  1.14893757e-01,
         9.02713984e-02, -4.92017627e-01,  1.73573509e-01,  4.50229973e-01,
        -2.85842806e-01, -1.60026044e-01, -1.21276893e-01, -3.83726746e-01,
        -2.84060352e-02,  1.08711928e-01,  2.11308733e-01, -1.56023115e-01,
         9.02521163e-02, -2.99215913e-01, -3.60065065e-02, -5.17517090e-01,
         2.09581196e-01,  1.11991480e-01,  1.08882822e-01, -2.22127736e-01,
        -4.31063436e-02, -3.17326933e-03, -2.12848976e-01, -1.89508304e-01,
        -2.46705920e-01,  4.57022451e-02,  3.01409036e-01,  2.47692466e-02,
         9.65628996e-02, -1.83762476e-01, -9.45831165e-02,  4.17984575e-01,
         8.56550410e-02, -1.26581490e-01, -1.43469885e-01, -4.53020930e-01,
         1.31902024e-01, -2.56371588e-01, -1.68852434e-01, -1.46145897e-03,
         1.51327714e-01, -1.20843817e-02, -1.49584323e-01, -2.95160674e-02,
         2.08835259e-01,  1.19421825e-01,  1.69513464e-01, -2.02265754e-01,
        -5.0

In [301]:
# Independent feature
X_new = np.array(X,dtype=object)

In [304]:
X_new[0]

array([-1.74621001e-01,  2.31070533e-01,  1.23805277e-01,  1.14893757e-01,
        9.02713984e-02, -4.92017627e-01,  1.73573509e-01,  4.50229973e-01,
       -2.85842806e-01, -1.60026044e-01, -1.21276893e-01, -3.83726746e-01,
       -2.84060352e-02,  1.08711928e-01,  2.11308733e-01, -1.56023115e-01,
        9.02521163e-02, -2.99215913e-01, -3.60065065e-02, -5.17517090e-01,
        2.09581196e-01,  1.11991480e-01,  1.08882822e-01, -2.22127736e-01,
       -4.31063436e-02, -3.17326933e-03, -2.12848976e-01, -1.89508304e-01,
       -2.46705920e-01,  4.57022451e-02,  3.01409036e-01,  2.47692466e-02,
        9.65628996e-02, -1.83762476e-01, -9.45831165e-02,  4.17984575e-01,
        8.56550410e-02, -1.26581490e-01, -1.43469885e-01, -4.53020930e-01,
        1.31902024e-01, -2.56371588e-01, -1.68852434e-01, -1.46145897e-03,
        1.51327714e-01, -1.20843817e-02, -1.49584323e-01, -2.95160674e-02,
        2.08835259e-01,  1.19421825e-01,  1.69513464e-01, -2.02265754e-01,
       -5.03616072e-02,  

In [306]:
X_new.shape

(5569,)

In [308]:
X_new[0].shape

(100,)

In [310]:
#Dependent Features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [312]:
#we found an issue
X_new.shape,y.shape

((5569,), (5569,))

#### Where did we lost 3 record , we lost it in preprocesiing techinique(converting corpus into word)

In [315]:
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [317]:
messages.shape

(5569, 2)

In [319]:
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [321]:
y.shape

(5569,)

In [323]:
X[0].reshape(1,-1).shape

(1, 100)

In [325]:
rows = []

for i in range(len(X)):
    rows.append(pd.Series(X[i].flatten()))

df = pd.DataFrame(rows)

In [326]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.174621,0.231071,0.123805,0.114894,0.090271,-0.492018,0.173574,0.450230,-0.285843,-0.160026,...,0.347544,0.179095,0.011647,0.054864,0.419738,0.193942,0.143700,-0.205792,0.150815,0.013616
1,-0.155081,0.200471,0.103726,0.099531,0.081683,-0.420528,0.138293,0.391168,-0.244461,-0.130080,...,0.300955,0.148031,0.005862,0.040520,0.348950,0.160569,0.122783,-0.182524,0.136140,0.004447
2,-0.186593,0.249376,0.136795,0.130467,0.081467,-0.539925,0.174818,0.438452,-0.302430,-0.185530,...,0.342940,0.189192,-0.001861,0.024361,0.424420,0.177861,0.096366,-0.232761,0.171409,0.040346
3,-0.239492,0.312085,0.159739,0.157921,0.122988,-0.661207,0.222934,0.613832,-0.388654,-0.205134,...,0.470557,0.236157,0.009740,0.078855,0.553747,0.265308,0.207844,-0.284264,0.203716,0.009752
4,-0.211271,0.259765,0.142921,0.131175,0.115428,-0.559986,0.188331,0.526710,-0.331387,-0.181879,...,0.403848,0.195233,0.012866,0.070656,0.469808,0.228532,0.170552,-0.252559,0.165170,0.009256


In [327]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [331]:
# Convert y (1D array) into DataFrame
y = pd.DataFrame(y, columns=['Target'])
y

,Target
0,True
1,True
2,False
3,True
4,True
...,...
5564,False
5565,True
5566,True
5567,True


In [354]:
df['Output']=y

In [356]:
df

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.174621,0.231071,0.123805,0.114894,0.090271,-0.492018,0.173574,0.450230,-0.285843,-0.160026,...,0.179095,0.011647,0.054864,0.419738,0.193942,0.143700,-0.205792,0.150815,0.013616,True
1,-0.155081,0.200471,0.103726,0.099531,0.081683,-0.420528,0.138293,0.391168,-0.244461,-0.130080,...,0.148031,0.005862,0.040520,0.348950,0.160569,0.122783,-0.182524,0.136140,0.004447,True
2,-0.186593,0.249376,0.136795,0.130467,0.081467,-0.539925,0.174818,0.438452,-0.302430,-0.185530,...,0.189192,-0.001861,0.024361,0.424420,0.177861,0.096366,-0.232761,0.171409,0.040346,False
3,-0.239492,0.312085,0.159739,0.157921,0.122988,-0.661207,0.222934,0.613832,-0.388654,-0.205134,...,0.236157,0.009740,0.078855,0.553747,0.265308,0.207844,-0.284264,0.203716,0.009752,True
4,-0.211271,0.259765,0.142921,0.131175,0.115428,-0.559986,0.188331,0.526710,-0.331387,-0.181879,...,0.195233,0.012866,0.070656,0.469808,0.228532,0.170552,-0.252559,0.165170,0.009256,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.206226,0.289933,0.169376,0.154360,0.100877,-0.605770,0.217718,0.519164,-0.351032,-0.209603,...,0.222082,0.013636,0.041027,0.505935,0.213640,0.132987,-0.254927,0.192634,0.038299,False
5565,-0.219187,0.269786,0.144109,0.144366,0.112348,-0.599116,0.195062,0.536927,-0.351441,-0.186727,...,0.212580,-0.005883,0.053074,0.495063,0.228534,0.150080,-0.269960,0.181912,0.024485,True
5566,-0.238119,0.315164,0.162076,0.147046,0.113146,-0.650458,0.232730,0.604360,-0.381010,-0.218066,...,0.246029,0.021921,0.089514,0.558888,0.266845,0.209284,-0.263066,0.193579,0.012496,True
5567,-0.216151,0.280981,0.147666,0.141410,0.108636,-0.596099,0.203742,0.541703,-0.345196,-0.199109,...,0.216122,0.018120,0.069552,0.502428,0.236135,0.168783,-0.249083,0.175081,0.011860,True


In [364]:
df.isnull().sum()

0         12
1         12
2         12
3         12
4         12
          ..
96        12
97        12
98        12
99        12
Output     0
Length: 101, dtype: int64

In [368]:
df.dropna(inplace=True)

In [370]:
df.isna().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [372]:
y=df['Output']

In [386]:
df.drop('Output',axis=1,inplace=True)

In [388]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.174621,0.231071,0.123805,0.114894,0.090271,-0.492018,0.173574,0.450230,-0.285843,-0.160026,...,0.347544,0.179095,0.011647,0.054864,0.419738,0.193942,0.143700,-0.205792,0.150815,0.013616
1,-0.155081,0.200471,0.103726,0.099531,0.081683,-0.420528,0.138293,0.391168,-0.244461,-0.130080,...,0.300955,0.148031,0.005862,0.040520,0.348950,0.160569,0.122783,-0.182524,0.136140,0.004447
2,-0.186593,0.249376,0.136795,0.130467,0.081467,-0.539925,0.174818,0.438452,-0.302430,-0.185530,...,0.342940,0.189192,-0.001861,0.024361,0.424420,0.177861,0.096366,-0.232761,0.171409,0.040346
3,-0.239492,0.312085,0.159739,0.157921,0.122988,-0.661207,0.222934,0.613832,-0.388654,-0.205134,...,0.470557,0.236157,0.009740,0.078855,0.553747,0.265308,0.207844,-0.284264,0.203716,0.009752
4,-0.211271,0.259765,0.142921,0.131175,0.115428,-0.559986,0.188331,0.526710,-0.331387,-0.181879,...,0.403848,0.195233,0.012866,0.070656,0.469808,0.228532,0.170552,-0.252559,0.165170,0.009256


In [390]:
y.head()

0     True
1     True
2    False
3     True
4     True
Name: Output, dtype: bool

In [402]:
X=df

In [404]:
X.shape,y.shape

((5557, 100), (5557,))

In [406]:
X

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.174621,0.231071,0.123805,0.114894,0.090271,-0.492018,0.173574,0.450230,-0.285843,-0.160026,...,0.347544,0.179095,0.011647,0.054864,0.419738,0.193942,0.143700,-0.205792,0.150815,0.013616
1,-0.155081,0.200471,0.103726,0.099531,0.081683,-0.420528,0.138293,0.391168,-0.244461,-0.130080,...,0.300955,0.148031,0.005862,0.040520,0.348950,0.160569,0.122783,-0.182524,0.136140,0.004447
2,-0.186593,0.249376,0.136795,0.130467,0.081467,-0.539925,0.174818,0.438452,-0.302430,-0.185530,...,0.342940,0.189192,-0.001861,0.024361,0.424420,0.177861,0.096366,-0.232761,0.171409,0.040346
3,-0.239492,0.312085,0.159739,0.157921,0.122988,-0.661207,0.222934,0.613832,-0.388654,-0.205134,...,0.470557,0.236157,0.009740,0.078855,0.553747,0.265308,0.207844,-0.284264,0.203716,0.009752
4,-0.211271,0.259765,0.142921,0.131175,0.115428,-0.559986,0.188331,0.526710,-0.331387,-0.181879,...,0.403848,0.195233,0.012866,0.070656,0.469808,0.228532,0.170552,-0.252559,0.165170,0.009256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.206226,0.289933,0.169376,0.154360,0.100877,-0.605770,0.217718,0.519164,-0.351032,-0.209603,...,0.408559,0.222082,0.013636,0.041027,0.505935,0.213640,0.132987,-0.254927,0.192634,0.038299
5565,-0.219187,0.269786,0.144109,0.144366,0.112348,-0.599116,0.195062,0.536927,-0.351441,-0.186727,...,0.416002,0.212580,-0.005883,0.053074,0.495063,0.228534,0.150080,-0.269960,0.181912,0.024485
5566,-0.238119,0.315164,0.162076,0.147046,0.113146,-0.650458,0.232730,0.604360,-0.381010,-0.218066,...,0.469549,0.246029,0.021921,0.089514,0.558888,0.266845,0.209284,-0.263066,0.193579,0.012496
5567,-0.216151,0.280981,0.147666,0.141410,0.108636,-0.596099,0.203742,0.541703,-0.345196,-0.199109,...,0.415145,0.216122,0.018120,0.069552,0.502428,0.236135,0.168783,-0.249083,0.175081,0.011860


In [408]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [410]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
1904,-0.162961,0.201710,0.109035,0.095240,0.083934,-0.420528,0.141506,0.396582,-0.245527,-0.138592,...,0.306281,0.153606,0.008225,0.047649,0.362299,0.172143,0.126990,-0.183163,0.127421,0.010222
2924,-0.163025,0.219820,0.113295,0.116150,0.079153,-0.461794,0.158766,0.413956,-0.262161,-0.155755,...,0.319788,0.171615,0.013239,0.047920,0.390960,0.177642,0.129050,-0.188702,0.142115,0.014280
3309,-0.231150,0.299503,0.163016,0.155585,0.116403,-0.640549,0.218394,0.583015,-0.377806,-0.201797,...,0.450216,0.228612,0.010989,0.062700,0.530367,0.244215,0.177888,-0.271298,0.195241,0.015982
5223,-0.101444,0.128056,0.071549,0.067516,0.051332,-0.285640,0.096650,0.251331,-0.166114,-0.090501,...,0.193555,0.102010,0.007555,0.025466,0.234651,0.117702,0.078179,-0.117444,0.085788,0.007269
2469,-0.251112,0.330343,0.183281,0.165876,0.116826,-0.689648,0.254530,0.626312,-0.407385,-0.220262,...,0.489561,0.260478,0.027894,0.077417,0.593495,0.289665,0.214339,-0.262672,0.209985,0.017175


In [412]:
y_train.head()

1904    True
2924    True
3309    True
5223    True
2469    True
Name: Output, dtype: bool

In [414]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [416]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [421]:
y_pred=classifier.predict(X_test)

In [423]:
y_pred

array([ True,  True,  True, ...,  True,  True,  True])

In [425]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9613309352517986


In [427]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.92      0.79      0.85       151
        True       0.97      0.99      0.98       961

    accuracy                           0.96      1112
   macro avg       0.94      0.89      0.91      1112
weighted avg       0.96      0.96      0.96      1112

